// CodeTemplates.kt
// Skill 创建器 - 代码模板库 (简化版)

package com.androidclaw.app.skills.creator

/**
 * 工具规格定义
 */
data class ToolSpec(
    val name: String,
    val description: String,
    val parameters: List<ToolParameterSpec>,
    val returnType: String
)

/**
 * 工具参数规格定义
 */
data class ToolParameterSpec(
    val name: String,
    val type: String,
    val required: Boolean,
    val description: String
)

/**
 * 代码模板库 (简化版)
 * 
 * 提供基础 Skill 模板
 */
object CodeTemplates {

    /**
     * 基础 Skill 模板 (简化版)
     */
    fun baseSkillTemplate(
        skillName: String,
        displayName: String,
        description: String,
        permissions: List<String>,
        tools: List<ToolSpec>
    ): String {
        return """
// ${skillName}.kt
// $description
// Auto-generated by AndroidClaw Skill Creator (Simplified)

package com.androidclaw.app.skills

import android.content.Context
import android.util.Log

/**
 * $displayName
 * $description
 */
class ${skillName.capitalize()}Skill : SkillDefinition {

    companion object {
        private const val TAG = "${skillName.toUpperCase()}_SKILL"
    }

    private var context: Context? = null

    override val skillName: String = "$skillName"
    override val displayName: String = "$displayName"
    override val description: String = "$description"
    override val requiredPermissions: List<String> = listOf(
        ${permissions.joinToString(",\n        ") { "\"$it\"" }}
    )

    override suspend fun initialize(context: Context) {
        this.context = context
        Log.i(TAG, "$displayName Skill initialized")
    }

    override fun getTools(): List<ToolDefinition> = listOf(
        ${tools.joinToString(",\n        ") { 
            """ToolDefinition(
            toolName = "${it.name}",
            displayName = "${it.description.take(20)}",
            description = "${it.description}",
            parameters = emptyList(),
            returnType = "${it.returnType}"
        )"""
        }}
    )

    override suspend fun executeTool(toolName: String, parameters: Map<String, Any>): ToolResult {
        return ToolResult.Success(mapOf("status" to "not_implemented"))
    }

    override fun release() {
        context = null
        Log.i(TAG, "$displayName Skill released")
    }
}
""".trimIndent()
    }

    /**
     * 简化版 - 其他方法暂时返回空字符串
     */
    fun httpGetTemplate(): String = "// HTTP GET template - simplified"
    fun httpPostTemplate(): String = "// HTTP POST template - simplified"
    fun notificationTemplate(): String = "// Notification template - simplified"
    fun fileOperationTemplate(): String = "// File operation template - simplified"
    fun broadcastReceiverTemplate(): String = "// Broadcast receiver template - simplified"
    fun foregroundServiceTemplate(): String = "// Foreground service template - simplified"
}
