// CodeTemplates.kt
// Skill 创建器 - 代码模板库
// 提供常用代码模板，加速 Skill 生成

package com.androidclaw.app.skills.creator

/**
 * 代码模板库
 * 
 * 提供以下模板：
 * - 基础 Skill 模板（实现 SkillDefinition 接口）
 * - 网络请求模板（HTTP GET/POST）
 * - 数据库操作模板（Room DAO）
 * - 文件操作模板
 * - 通知模板
 * - 广播接收器模板
 * - 服务模板（Foreground Service）
 */
object CodeTemplates {

    /**
     * 基础 Skill 模板
     */
    fun baseSkillTemplate(
        skillName: String,
        displayName: String,
        description: String,
        permissions: List<String>,
        tools: List<ToolSpec>
    ): String {
        val permissionList = if (permissions.isNotEmpty()) {
            permissions.joinToString(",\n        ") { 
                val permName = it.substringAfterLast(".")
                "android.Manifest.permission.$permName"
            }
        } else {
            ""
        }
        
        val toolsList = tools.mapIndexed { index, tool ->
            """
        ToolDefinition(
            toolName = "${tool.name}",
            displayName = "${tool.description.take(20)}",
            description = "${tool.description}",
            parameters = listOf(
                ${tool.parameters.joinToString(",\n                ") { param ->
                    """ToolParameter("${param.name}", "${param.type}", ${param.required}, "${param.description}")"""
                }}
            ),
            returnType = "${tool.returnType}"
        )${if (index < tools.size - 1) "," else ""}
            """
        }.joinToString("\n")

        return """
// ${skillName.replace("_", " ").capitalize()}.kt
// ${description}
// Auto-generated by AndroidClaw Skill Creator

package com.androidclaw.app.skills

import android.content.Context
import android.util.Log
${generateImports(tools)}

/**
 * ${displayName}
 * ${description}
 */
class ${skillName.split("_").joinToString("") { it.capitalize() }}Skill : SkillDefinition {

    companion object {
        private const val TAG = "${skillName.capitalize()}Skill"
    }

    private var context: Context? = null

    override val skillName: String = "$skillName"
    override val displayName: String = "$displayName"
    override val description: String = "$description"
    override val requiredPermissions: List<String> = listOf(
        $permissionList
    )

    override suspend fun initialize(context: Context) {
        this.context = context
        Log.i(TAG, "${displayName}Skill initialized")
    }

    override fun getTools(): List<ToolDefinition> = listOf(
$toolsList
    )

    override suspend fun executeTool(toolName: String, parameters: Map<String, Any>): ToolResult {
        return try {
            when (toolName) {
                ${tools.joinToString("\n                ") { tool -> 
                    "\"${tool.name}\" -> execute${tool.name.capitalize()}(parameters)"
                }}
                else -> ToolResult.Error("Unknown tool: \$toolName")
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error executing \$toolName", e)
            ToolResult.Error("执行失败: \${e.message}", e)
        }
    }

    ${tools.joinToString("\n\n    ") { tool -> generateToolMethod(tool) }}

    override fun release() {
        context = null
        Log.i(TAG, "${displayName}Skill released")
    }
}
""".trimIndent()
    }

    /**
     * 生成导入语句
     */
    private fun generateImports(tools: List<ToolSpec>): String {
        val imports = mutableSetOf<String>()
        
        // 检查是否需要网络
        if (tools.any { it.returnType == "map" || it.parameters.any { p -> p.type == "map" } }) {
            imports.add("import org.json.JSONObject")
            imports.add("import com.google.gson.Gson")
            imports.add("import com.google.gson.reflect.TypeToken")
        }
        
        return imports.joinToString("\n")
    }

    /**
     * 生成工具方法
     */
    private fun generateToolMethod(tool: ToolSpec): String {
        val params = tool.parameters.joinToString(", ") { param ->
            val paramRef = when (param.type) {
                "string" -> "params[\"${param.name}\"] as? String ?: \"\""
                "int" -> "(params[\"${param.name}\"] as? Number)?.toInt() ?: 0"
                "boolean" -> "params[\"${param.name}\"] as? Boolean ?: false"
                "float" -> "(params[\"${param.name}\"] as? Number)?.toFloat() ?: 0f"
                else -> "params[\"${param.name}\"]"
            }
            paramRef
        }
        
        return """
    private suspend fun execute${tool.name.capitalize()}(params: Map<String, Any>): ToolResult {
        Log.d(TAG, "Executing ${tool.name} with params: \$params")
        
        // TODO: 实现具体逻辑
        // 参数: ${tool.parameters.joinToString(", ") { "${it.name}: ${it.type}" }}
        
        return ToolResult.Success(mapOf(
            "status" to "success",
            "message" to "功能待实现"
        ))
    }
""".trimIndent()
    }

    /**
     * 网络请求模板 - GET
     */
    fun httpGetTemplate(): String = """
    /**
     * HTTP GET 请求
     */
    private suspend fun httpGet(url: String): String = withContext(Dispatchers.IO) {
        val connection = URL(url).openConnection() as HttpURLConnection
        try {
            connection.requestMethod = "GET"
            connection.connectTimeout = 10000
            connection.readTimeout = 10000
            connection.setRequestProperty("Accept", "application/json")
            
            val responseCode = connection.responseCode
            if (responseCode == HttpURLConnection.HTTP_OK) {
                connection.inputStream.bufferedReader().use { it.readText() }
            } else {
                throw IOException("HTTP error: \$responseCode")
            }
        } finally {
            connection.disconnect()
        }
    }
"""

    /**
     * 网络请求模板 - POST
     */
    fun httpPostTemplate(): String = """
    /**
     * HTTP POST 请求
     */
    private suspend fun httpPost(url: String, jsonBody: String): String = withContext(Dispatchers.IO) {
        val connection = URL(url).openConnection() as HttpURLConnection
        try {
            connection.requestMethod = "POST"
            connection.connectTimeout = 10000
            connection.readTimeout = 10000
            connection.doOutput = true
            connection.setRequestProperty("Content-Type", "application/json")
            connection.setRequestProperty("Accept", "application/json")
            
            connection.outputStream.use { os ->
                val input = jsonBody.toByteArray(Charsets.UTF_8)
                os.write(input, 0, input.size)
            }
            
            val responseCode = connection.responseCode
            if (responseCode == HttpURLConnection.HTTP_OK) {
                connection.inputStream.bufferedReader().use { it.readText() }
            } else {
                throw IOException("HTTP error: \$responseCode")
            }
        } finally {
            connection.disconnect()
        }
    }
"""

    /**
     * 通知模板
     */
    fun notificationTemplate(): String = """
    /**
     * 发送通知
     */
    private fun showNotification(title: String, message: String, channelId: String = "default") {
        val context = this.context ?: return
        
        val notificationManager = context.getSystemService(Context.NOTIFICATION_SERVICE) 
            as NotificationManager
        
        // 创建通知渠道 (Android 8.0+)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                channelId,
                "Default Channel",
                NotificationManager.IMPORTANCE_DEFAULT
            )
            notificationManager.createNotificationChannel(channel)
        }
        
        val notification = NotificationCompat.Builder(context, channelId)
            .setSmallIcon(R.drawable.ic_notification)
            .setContentTitle(title)
            .setContentText(message)
            .setAutoCancel(true)
            .build()
        
        notificationManager.notify(System.currentTimeMillis().toInt(), notification)
    }
"""

    /**
     * 文件操作模板 - 读取
     */
    fun fileReadTemplate(): String = """
    /**
     * 读取文件内容
     */
    private fun readFile(filePath: String): String? {
        val context = this.context ?: return null
        
        return try {
            val file = File(filePath)
            if (file.exists()) {
                file.readText()
            } else {
                null
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to read file: \$filePath", e)
            null
        }
    }
"""

    /**
     * 文件操作模板 - 写入
     */
    fun fileWriteTemplate(): String = """
    /**
     * 写入文件内容
     */
    private fun writeFile(filePath: String, content: String): Boolean {
        val context = this.context ?: return false
        
        return try {
            val file = File(filePath)
            file.parentFile?.mkdirs()
            file.writeText(content)
            true
        } catch (e: Exception) {
            Log.e(TAG, "Failed to write file: \$filePath", e)
            false
        }
    }
"""

    /**
     * SharedPreferences 模板
     */
    fun sharedPreferencesTemplate(): String = """
    /**
     * 保存数据到 SharedPreferences
     */
    private fun savePreference(key: String, value: Any) {
        val context = this.context ?: return
        val prefs = context.getSharedPreferences("\${skillName}_prefs", Context.MODE_PRIVATE)
        
        prefs.edit().apply {
            when (value) {
                is String -> putString(key, value)
                is Int -> putInt(key, value)
                is Long -> putLong(key, value)
                is Boolean -> putBoolean(key, value)
                is Float -> putFloat(key, value)
            }
            apply()
        }
    }
    
    /**
     * 从 SharedPreferences 读取数据
     */
    private fun <T> getPreference(key: String, defaultValue: T): T {
        val context = this.context ?: return defaultValue
        val prefs = context.getSharedPreferences("\${skillName}_prefs", Context.MODE_PRIVATE)
        
        @Suppress("UNCHECKED_CAST")
        return when (defaultValue) {
            is String -> prefs.getString(key, defaultValue) as T
            is Int -> prefs.getInt(key, defaultValue) as T
            is Long -> prefs.getLong(key, defaultValue) as T
            is Boolean -> prefs.getBoolean(key, defaultValue) as T
            is Float -> prefs.getFloat(key, defaultValue) as T
            else -> defaultValue
        }
    }
"""

    /**
     * Intent 启动模板
     */
    fun intentTemplate(): String = """
    /**
     * 启动 Activity
     */
    private fun startActivity(action: String, dataUri: Uri? = null, extras: Map<String, Any>? = null) {
        val context = this.context ?: return
        
        val intent = Intent(action).apply {
            dataUri?.let { data = it }
            extras?.forEach { (key, value) ->
                when (value) {
                    is String -> putExtra(key, value)
                    is Int -> putExtra(key, value)
                    is Boolean -> putExtra(key, value)
                    is Long -> putExtra(key, value)
                }
            }
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        
        context.startActivity(intent)
    }
"""

    /**
     * 生成 skill_manifest.json
     */
    fun manifestTemplate(
        skillName: String,
        displayName: String,
        description: String,
        version: String = "1.0.0",
        author: String = "AndroidClaw User",
        permissions: List<String>,
        tools: List<ToolSpec>
    ): String {
        val manifestTools = tools.joinToString(",\n") { tool ->
            """
        {
          "name": "${tool.name}",
          "description": "${tool.description}",
          "parameters": [
            ${tool.parameters.joinToString(",\n            ") { param ->
                """{"name": "${param.name}", "type": "${param.type}", "required": ${param.required}, "description": "${param.description}"}"""
            }}
          ]
        }"""
        }

        return """
{
  "name": "$skillName",
  "version": "$version",
  "display_name": "$displayName",
  "description": "$description",
  "author": "$author",
  "license": "Apache-2.0",
  "min_androidclaw_version": "1.0.0",
  "permissions": [
    ${permissions.joinToString(",\n    ") { "\"$it\"" }}
  ],
  "entry_point": "${skillName}_skill.kt",
  "tools": [$manifestTools
  ],
  "assets": [],
  "dependencies": []
}
""".trimIndent()
    }

    /**
     * 生成 README.md
     */
    fun readmeTemplate(
        skillName: String,
        displayName: String,
        description: String,
        tools: List<ToolSpec>,
        permissions: List<String>
    ): String {
        return """
# $displayName

$description

## 功能工具

${tools.joinToString("\n") { tool ->
    "- **${tool.name}**: ${tool.description}"
}}

## 所需权限

${if (permissions.isNotEmpty()) {
    permissions.joinToString("\n") { "- `$it`" }
} else {
    "无特殊权限要求"
}}

## 使用示例

```
用户: 帮我${description.take(20)}...
Agent: [调用 ${tools.firstOrNull()?.name ?: "execute"} 工具]
```

## 注意事项

- 此 Skill 由 AI 自动生成，请在使用前检查代码安全性
- 如有问题，请在 AndroidClaw 社区反馈

---
*Generated by AndroidClaw Skill Creator*
""".trimIndent()
    }
}
